### ISSUE TITLE
Question : I couldn't find support for polyhedral cell types in OpenVKL. Is there any way I could use polyhedral cells data? Is there any plan for supporting it in future?

### ISSUE THREAD

**Issue by kuldip-wagh** [RenderKit/openvkl#16]
I couldn't find support for polyhedral cell types in OpenVKL. Is there any way I could use polyhedral cells data? Is there any plan for supporting it in future?

I have cells of tetrahedron, hexahedron, wedge, pyramid, polyhedral and mixed. Hence polyhedral seems to be important to have support in openVKL. I currently using unstructured type to have support for other 4 cell types.

**Comment by kuldip-wagh** [comment]
Hello,

I have polyhedral cells with NF faces, NP points where N is any generic number. Hence it can be considered as general polyhedron.

**Comment by kuldip-wagh** [comment]
Hello,
Is there any update for polyhedral support? Anything new?

**Comment by gregjohnson** [comment]
Hello @kuldip-wagh , unfortunately we are not able to commit to developing this feature at this time, and therefore can't provide any timeline. However, we're open to accepting pull requests if this is a feature you / others are interested in contributing.

**Comment by kuldip-wagh** [comment]
Hello @kraszkow, as you completed it. Does it mean that polyheral cell type is added?
