### ISSUE TITLE
question: multi-attribute unstructured queries?

### ISSUE THREAD

**Issue by timsandstrom** [RenderKit/openvkl#22]
I hope my nomenclature is correct....

I'm wondering if there will be support for sampling vec3f on an unstrctured volume similar to structured....
[I know this is may be hard]

i.e. vec3f v = VKLUnstructuredVolume_sample(...)

We could use this, for example, to sample a vector field, useful for particle advection in unstructured volumes...

Otherwise, it seems like we'd have to create a volume/sampler for each component... could be expensive for us memorywise...

I do see some internal use of with particle sampling but nothing exposed by the api... any hope?

Thanks in advance for help/suggestions, openvkl/ospray remains fairly essential for our group.
-Tim

  // sample (multiple attributes)
  unsigned int M                  = 3;
  unsigned int attributeIndices[] = {0, 1, 2};
  float samples[3];
  vklComputeSampleM(&sampler, &coord, samples, M, attributeIndices, time);
  printf("\tsampling (multiple attributes)\n");
  printf("\t\tsamples = %f %f %f\n\n", samples[0], samples[1], samples[2]);

**Comment by gregjohnson** [comment]
Hi Tim,
You're correct that unstructured volumes do not support multiple attributes as some of the other volume types do (e.g. structured regular volumes). So, unfortunately the only solution now is to create / sample separate volumes for each vec3f component -- which I know is inefficient in multiple ways.

We don't have multi-attribute support for unstructured volumes planned at this point, which means we won't be able to address it this quarter.

**Comment by timsandstrom** [comment]
Hey Greg, thanks for the reply and the continued support.

I'm working on calling ispc from c++, manually walking the bvh, using the cell-weights to interpolate vec3fa's at the nodes...

-Tim

**Comment by gregjohnson** [comment]
Thanks Tim, and sorry we're not able to more fully support this right now. If you have questions, definitely let us know -- we can also schedule a meeting to go over code questions, etc.
