### ISSUE TITLE
Does the "particles" volumes support Multi-attributes ?

### ISSUE THREAD

**Issue by elzeru** [RenderKit/openvkl#23]
Hi, 

Does the "particles" volumes support Multi-attributes ? If yes, are the attributes interpolated using the radial basis functions ?

I need an additional parameter to color the particles. I am using vklSetData( myVolume, "data", attributesData ) and I am trying to sample it with vklComputeSampleM but it doesn't work.

Thanks.

**Comment by gregjohnson** [comment]
Hello,
Particle volumes do not currently support multiple attributes, but rather a single scalar attribute as you've seen. Currently only `structuredRegular`, `structuredSpherical`, and `vdb` volumes support multiple attributes.

Currently you would need to create an additional volume for the value you want to map to colors. This could be another particle volume, or you could resample the color values onto e.g. a `structuredRegular` grid (which may be more performant, but it depends on the details / requirements of your color-by data).

**Comment by elzeru** [comment]
Thanks for your answer !
